---
debug : False                                                     # will toggle the debug prints
window : True                                                     # will toggle the TKinter window
URLS:                                                             # list of premium articles
  - https://www.nzherald.co.nz/business/covid-19-delta-outbreak-andrew-barnes-on-miq-and-the-vaccinated-time-to-let-people-go-and-come-home/V5EBW5GK6N46GXEVX5F4HPUFXQ/