---
debug : False                                                     # will toggle the debug prints
window : True                                                     # will toggle the TKinter window
URLS:                                                             # list of premium articles
  - https://www.nzherald.co.nz/business/what-working-from-home-does-to-your-brain/G3KYTJVLZFX7UDNB3UXRMNVVPU/